import { existsSync, mkdirSync, readFileSync, readdirSync, renameSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import {
  assert,
  assertInt,
  canonicalStringify,
  divFloor,
  isJsonObject,
  type JsonObject,
  type JsonValue,
} from '@rpgsim/shared';
import {
  type CalendarConfig,
  DEFAULT_CALENDAR,
  TICKS_PER_DAY,
  type Tick,
  tickToDateTime,
} from './calendar.ts';
import { type EventSink, eventFromJson, eventToJson } from './event-log.ts';
import type { SimEvent } from './events.ts';

/**
 * Durable event history, one file per simulated day.
 *
 * `EventLog` keeps a bounded window in memory on purpose — unbounded event
 * growth is a named failure mode in CLAUDE.md — so anything that needs the
 * whole of a day, or weeks of it, reads from here instead. `docs/CHRONICLE.md`
 * section 3 is why this exists: a daily paper needs the whole day, continuing
 * stories need weeks, and an archive needs the year.
 *
 * Three decisions worth knowing before reading the code, all recorded in
 * `docs/CHRONICLE_V1.md` section 2:
 *
 * **A day is the unit.** It is the unit the chronicle reads and the unit the
 * site publishes, and a day file that exists is a day that is final.
 *
 * **A day is buffered and written whole**, through a temporary file and a
 * rename, so it is either complete or absent and never torn. That is the
 * opposite of the trade made for saves: losing a save loses state that cannot
 * be recovered, whereas a lost day can be regenerated by re-running the seed.
 * The cost is that an in-progress day lives in memory — about fifteen events
 * per villager per Phase 1 day, which is nothing, and which is the number to
 * revisit when a day gets busy.
 *
 * **Lines are canonical JSON.** Two runs of one seed produce byte-identical
 * archives, so a diff of two archives is a readable diff of two histories.
 */

/** Everything an archive writes lives under these two names. */
const DAYS_DIRECTORY = 'days';
const EVENTS_FILE = 'events.jsonl';
const MANIFEST_FILE = 'manifest.json';
const TEMPORARY_SUFFIX = '.writing';

/** `1200-04-01`. Sorts chronologically as a string, which the archive relies on. */
export function dayKeyOf(tick: Tick, calendar: CalendarConfig = DEFAULT_CALENDAR): string {
  const date = tickToDateTime(tick, calendar);
  const year = String(date.year).padStart(4, '0');
  const month = String(date.month).padStart(2, '0');
  const day = String(date.day).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

/** Absolute day index, the value the sink actually rolls on. */
export function dayIndexOf(tick: Tick): number {
  assertInt(tick, 'tick must be an integer');
  assert(tick >= 0, 'tick must not be negative', { tick });
  return divFloor(tick, TICKS_PER_DAY);
}

/** One day's entry in the manifest. */
export interface ArchivedDay {
  /** `1200-04-01`. The directory name too. */
  readonly key: string;
  readonly dayIndex: number;
  /** First and last tick of the day, inclusive; the day's boundaries, not its events'. */
  readonly firstTick: Tick;
  readonly lastTick: Tick;
  readonly events: number;
  /**
   * The world's state hash at the end of the day, when a driver supplied one.
   *
   * `null` when the day was closed by a tick rolling past it rather than by an
   * explicit `sealDay`. A day without a hash can be read; it just cannot take
   * part in the frozen-history check, because there is nothing to compare.
   */
  readonly hash: string | null;
}

export interface ArchiveManifest {
  readonly world: string;
  readonly seed: string;
  /**
   * Whether the run that wrote this archive finished and closed it.
   *
   * A manifest is rewritten as each day lands, so an archive is readable while
   * it is still being written — which is what makes an interrupted run
   * salvageable. It also means "there is a manifest" does not mean "the run
   * finished", and a publisher that cannot tell the difference will happily
   * print a paper from a day the simulation died in the middle of.
   */
  readonly complete: boolean;
  /** Chronological. Gaps are possible and legal: a world can be archived in pieces. */
  readonly days: readonly ArchivedDay[];
}

export interface EventArchiveOptions {
  /** Directory the archive owns. Created if missing. */
  readonly root: string;
  readonly world: string;
  readonly seed: string;
  readonly calendar?: CalendarConfig;
  /**
   * Allow writing over day files this archive did not write itself.
   *
   * Off by default, because re-running a world that has already been archived
   * is easy to do by accident and the silent result would be a day whose events
   * happened twice. `docs/CHRONICLE_V1.md` turns this into the launch freeze:
   * while the world is young, rewriting is asked for explicitly; once history
   * is frozen, it stops being asked for.
   */
  readonly rewrite?: boolean;
  /** Sink id, for `EventLog.addSink`. */
  readonly id?: string;
}

/**
 * An `EventSink` that writes simulated days to disk.
 *
 * Attach it to an `EventLog` and run. It rolls to a new file whenever an
 * event's tick crosses a day boundary, so a driver that runs thirty days in one
 * call still gets thirty files. A driver that wants the state hash recorded
 * against each day runs a day at a time and calls `sealDay` in between.
 */
export class EventArchive implements EventSink {
  readonly id: string;
  readonly root: string;
  readonly world: string;
  readonly seed: string;

  private readonly calendar: CalendarConfig;
  private readonly rewrite: boolean;
  /** Days this instance has written, so its own re-writes are not refusals. */
  private readonly written = new Set<string>();
  private readonly days: ArchivedDay[] = [];

  private closed = false;
  private openDayIndex: number | null = null;
  /** Highest day index already written out. Nothing may be added to it again. */
  private closedThrough: number | null = null;
  private buffer: SimEvent[] = [];
  private lastTick = -1;

  constructor(options: EventArchiveOptions) {
    this.id = options.id ?? 'event-archive';
    this.root = resolve(options.root);
    this.world = options.world;
    this.seed = options.seed;
    this.calendar = options.calendar ?? DEFAULT_CALENDAR;
    this.rewrite = options.rewrite ?? false;
    assert(this.world.length > 0, 'archive world name must not be empty');
    assert(this.seed.length > 0, 'archive seed must not be empty');
    mkdirSync(join(this.root, DAYS_DIRECTORY), { recursive: true });
  }

  write(event: SimEvent): void {
    // The kernel emits in tick order. A tick going backwards means the sink is
    // attached to a world that was rewound underneath it, which would interleave
    // two histories in one file; sim-core rule 10 says say so rather than cope.
    assert(event.tick >= this.lastTick, 'events reached the archive out of tick order', {
      tick: event.tick,
      previous: this.lastTick,
    });
    this.lastTick = event.tick;

    // A day that has been written out is finished. Re-opening it would either
    // duplicate its manifest entry or silently rewrite a published file, and a
    // driver that seals a day and then keeps running is a driver with a bug.
    const dayIndex = dayIndexOf(event.tick);
    assert(
      this.closedThrough === null || dayIndex > this.closedThrough,
      'an event arrived for a day the archive has already closed',
      { day: dayIndex, closedThrough: this.closedThrough },
    );

    if (this.openDayIndex === null) {
      this.openDayIndex = dayIndex;
    } else if (dayIndex !== this.openDayIndex) {
      this.closeDay(null);
      this.openDayIndex = dayIndex;
    }
    this.buffer.push(event);
  }

  /**
   * Write the open day to disk without closing it.
   *
   * The whole day is held in memory until it rolls, so flushing twice simply
   * rewrites the same file with more in it. That is what makes an interrupted
   * run leave a readable partial day rather than nothing.
   */
  flush(): void {
    if (this.openDayIndex === null) return;
    this.writeDayFile(this.openDayIndex, this.buffer);
    // The manifest goes out second, and only once the day file is safely down,
    // so a refused overwrite leaves the manifest that was already there alone.
    // It says `complete: false` until close(), which is the whole point: a
    // reader that finds a partial day also finds the warning attached to it.
    this.writeManifest();
  }

  /**
   * Finish a named day and record the world's state hash against it.
   *
   * Called by a driver that runs a day at a time. The day is named rather than
   * implied, so that a day in which nothing at all happened is still written —
   * a silent village is a fact about the world, and an absent file would be
   * indistinguishable from a day nobody simulated, which is exactly the
   * ambiguity `readEventDay` refuses to paper over.
   *
   * The hash is the evidence the launch freeze checks: a rebuild that produces
   * a different hash for a published day has rewritten history, and
   * `docs/CHRONICLE_V1.md` slice 7 fails the build rather than publishing it.
   */
  sealDay(dayIndex: number, hash: string | null = null): void {
    assertInt(dayIndex, 'day index must be an integer');
    assert(dayIndex >= 0, 'day index must not be negative', { day: dayIndex });

    // The day may already have rolled shut on its own, because a driver that
    // runs "up to and including the first tick of tomorrow" hands the archive
    // an event belonging to tomorrow before it gets a chance to seal today.
    // That is the normal path, not an error: the hash is taken at the instant
    // the boundary was crossed, and that instant is the same one either way.
    if (this.closedThrough === dayIndex) {
      const last = this.days[this.days.length - 1] as ArchivedDay;
      assert(last.dayIndex === dayIndex, 'the day just closed is not the one being sealed', {
        day: dayIndex,
        closed: last.dayIndex,
      });
      assert(last.hash === null, 'that day has already been sealed with a hash', { day: dayIndex });
      this.days[this.days.length - 1] = { ...last, hash };
      this.writeManifest();
      return;
    }

    assert(
      this.closedThrough === null || dayIndex > this.closedThrough,
      'that day has already been closed',
      { day: dayIndex, closedThrough: this.closedThrough },
    );

    if (this.openDayIndex === null) {
      this.writeDayFile(dayIndex, []);
      this.recordDay(dayIndex, 0, hash);
      this.closedThrough = dayIndex;
      return;
    }
    assert(this.openDayIndex === dayIndex, 'a different day is open', {
      asked: dayIndex,
      open: this.openDayIndex,
    });
    this.closeDay(hash);
  }

  /** Close the open day and mark the archive complete. */
  close(): void {
    if (this.openDayIndex !== null) this.closeDay(null);
    this.closed = true;
    this.writeManifest();
  }

  /** The manifest as it stands, without writing it. */
  manifest(): ArchiveManifest {
    return { world: this.world, seed: this.seed, complete: this.closed, days: [...this.days] };
  }

  private closeDay(hash: string | null): void {
    const dayIndex = this.openDayIndex as number;
    this.writeDayFile(dayIndex, this.buffer);
    this.recordDay(dayIndex, this.buffer.length, hash);
    this.buffer = [];
    this.openDayIndex = null;
    this.closedThrough = dayIndex;
  }

  private recordDay(dayIndex: number, events: number, hash: string | null): void {
    const firstTick = dayIndex * TICKS_PER_DAY;
    this.days.push({
      key: dayKeyOf(firstTick, this.calendar),
      dayIndex,
      firstTick,
      lastTick: firstTick + TICKS_PER_DAY - 1,
      events,
      hash,
    });
    this.writeManifest();
  }

  private writeDayFile(dayIndex: number, events: readonly SimEvent[]): void {
    const key = dayKeyOf(dayIndex * TICKS_PER_DAY, this.calendar);
    const directory = join(this.root, DAYS_DIRECTORY, key);
    const path = join(directory, EVENTS_FILE);

    if (!this.written.has(key) && existsSync(path) && !this.rewrite) {
      throw new Error(
        `the archive at ${this.root} already holds ${key}; pass rewrite to replace it`,
      );
    }

    mkdirSync(directory, { recursive: true });
    const body = events.map((event) => canonicalStringify(eventToJson(event))).join('\n');
    writeAtomically(path, events.length > 0 ? `${body}\n` : '');
    this.written.add(key);
  }

  private writeManifest(): void {
    writeAtomically(
      join(this.root, MANIFEST_FILE),
      `${canonicalStringify(manifestToJson(this.manifest()))}\n`,
    );
  }
}

/**
 * Write through a temporary file and a rename.
 *
 * A reader therefore sees the old contents or the new ones, never half of
 * either. `renameSync` replaces an existing destination on every platform Node
 * supports, which is the property this depends on.
 */
function writeAtomically(path: string, body: string): void {
  const temporary = `${path}${TEMPORARY_SUFFIX}`;
  writeFileSync(temporary, body, 'utf8');
  renameSync(temporary, path);
}

function manifestToJson(manifest: ArchiveManifest): JsonObject {
  return {
    world: manifest.world,
    seed: manifest.seed,
    complete: manifest.complete,
    days: manifest.days.map((day) => ({
      key: day.key,
      dayIndex: day.dayIndex,
      firstTick: day.firstTick,
      lastTick: day.lastTick,
      events: day.events,
      hash: day.hash,
    })),
  };
}

/** Read an archive's manifest. `undefined` when the archive has never been written. */
export function readArchiveManifest(root: string): ArchiveManifest | undefined {
  const path = join(resolve(root), MANIFEST_FILE);
  if (!existsSync(path)) return undefined;

  const value = JSON.parse(readFileSync(path, 'utf8')) as JsonValue;
  assert(isJsonObject(value), 'archive manifest must be an object', { path });
  const world = value['world'];
  const seed = value['seed'];
  const complete = value['complete'];
  const days = value['days'];
  assert(typeof world === 'string', 'archive manifest is missing world', { path });
  assert(typeof seed === 'string', 'archive manifest is missing seed', { path });
  assert(typeof complete === 'boolean', 'archive manifest is missing complete', { path });
  assert(Array.isArray(days), 'archive manifest is missing days', { path });

  return {
    world,
    seed,
    complete,
    days: days.map((entry, index) => parseArchivedDay(entry, path, index)),
  };
}

function parseArchivedDay(entry: JsonValue, path: string, index: number): ArchivedDay {
  assert(isJsonObject(entry), 'archive manifest day must be an object', { path, index });
  const key = entry['key'];
  const dayIndex = entry['dayIndex'];
  const firstTick = entry['firstTick'];
  const lastTick = entry['lastTick'];
  const events = entry['events'];
  const hash = entry['hash'];
  assert(typeof key === 'string', 'archived day is missing key', { path, index });
  assert(typeof dayIndex === 'number', 'archived day is missing dayIndex', { path, key });
  assert(typeof firstTick === 'number', 'archived day is missing firstTick', { path, key });
  assert(typeof lastTick === 'number', 'archived day is missing lastTick', { path, key });
  assert(typeof events === 'number', 'archived day is missing events', { path, key });
  assert(hash === null || typeof hash === 'string', 'archived day hash must be a string or null', {
    path,
    key,
  });
  return { key, dayIndex, firstTick, lastTick, events, hash: hash as string | null };
}

/** Day keys present on disk, chronological. Used to check the manifest against reality. */
export function listArchivedDays(root: string): string[] {
  const directory = join(resolve(root), DAYS_DIRECTORY);
  if (!existsSync(directory)) return [];
  return readdirSync(directory)
    .filter((name) => existsSync(join(directory, name, EVENTS_FILE)))
    .sort();
}

/**
 * Read one archived day.
 *
 * Throws when the day is absent. An absent day is not an empty day: a silent
 * village writes a file with nothing in it, so returning `[]` for a missing one
 * would be exactly the silent correction sim-core rule 10 forbids — and the way
 * a paper gets published for a day that was never simulated.
 */
export function readEventDay(root: string, key: string): SimEvent[] {
  const path = join(resolve(root), DAYS_DIRECTORY, key, EVENTS_FILE);
  if (!existsSync(path)) {
    throw new Error(`the archive at ${resolve(root)} has no day ${key}`);
  }

  const text = readFileSync(path, 'utf8');
  if (text.length === 0) return [];
  assert(text.endsWith('\n'), 'archived day does not end in a newline; it was truncated', { path });

  const lines = text.slice(0, -1).split('\n');
  return lines.map((line, index) => {
    let parsed: JsonValue;
    try {
      parsed = JSON.parse(line) as JsonValue;
    } catch (error) {
      throw new Error(`${path}:${index + 1} is not valid JSON: ${(error as Error).message}`);
    }
    try {
      return eventFromJson(parsed as JsonValue);
    } catch (error) {
      throw new Error(`${path}:${index + 1} is not a valid event: ${(error as Error).message}`);
    }
  });
}
